### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by whym** [AlexeyG/PySAIS#4]
It would be nice if you can release this under a clear license. It will make it easier for people to use it to build a larger piece of software. It could encourage contributions, too.

Would you like to choose [the MIT license](http://mit-license.org/) (as Yuta Mori did for sais.c and sais.h)?

**Comment by AlexeyG** [comment]
Sure. That would simply include adding the license text in source files and/or a license statement in the README?

**Comment by whym** [comment]
I believe a file named "LICENSE" is a standard method. Mentioning it in the readme would be great, too. [See also this guide](https://help.github.com/articles/open-source-licensing/).

**Comment by AlexeyG** [comment]
Added a reference to the LICENSE file. Should be satisfactory I suppose.
